name: Run Postgres script

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Pull repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Start PostgreSQL
      - name: Start database
        run: |
          docker compose up -d

      # Wait for PostgreSQL
      - name: Wait for PostgreSQL
        run: |
          until docker exec mydb pg_isready -U postgres; do
            echo "Waiting for database..."
            sleep 2
          done

      # Make script executable
      - name: Make script executable
        run: chmod +x run-postgres.sh

      # Run your script
      - name: Run script
        run: ./run-postgres.sh

      # Install kind
      - name: Set up KinD
        uses: engineerd/setup-kind@v0.6.0
        with:
          version: v0.20.0

      # Create a cluster
      - name: Create KinD cluster
        run: kind create cluster --name my-cluster

      # Install kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.27.3"

      # Deploy
      - name: Deploy PostgreSQL
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl rollout status deployment/postgres
